### ISSUE TITLE
hmr not work

### ISSUE THREAD

**Issue by a1mersnow** [MellowCo/unocss-webpack-uniapp2#1]
I must reload the page to see the new style

**Comment by MellowCo** [comment]
https://user-images.githubusercontent.com/47939250/233823918-30e43553-5410-4a12-ae70-13b554d7412c.mp4

没出现问题

```json
  "unocss": "^0.51.6",
  "unocss-preset-weapp": "^0.5.3",
  "unocss-webpack-uniapp2": "^0.1.4",
```

**Comment by a1mersnow** [comment]
You change `from-#f39c/60` to `from-#f39c12` which is already exist in your source code below...
What if you change it to `from-yellow`

**Comment by a1mersnow** [comment]
I tried the @unocss/webpack too, it have hmr problem too but not the same as this.

**Comment by MellowCo** [comment]
> You change `from-#f39c/60` to `from-#f39c12` which is already exist in your source code below... What if you change it to `from-yellow`


https://user-images.githubusercontent.com/47939250/233825064-3765f1cf-55a5-4653-b759-3eb069b6b0cd.mp4

**Comment by a1mersnow** [comment]
I just notice that you are using the miniapp...
HMR is a h5-specific behavior...

**Comment by MellowCo** [comment]
I don't know why this problem arises.
Most of the development time of UniApp is focused on MiniApp.
There is no plan to troubleshoot this issue.

**Comment by a1mersnow** [comment]
Allright
